package gov.nysenate.ess.supply.authorization.responsibilityhead;

import com.google.common.base.Preconditions;

import java.time.LocalDateTime;
import java.util.Objects;

public class TempResponsibilityHead {

    private Integer id;
    private final int employeeId;
    private final String responsibilityHeadCode;
    private final LocalDateTime startDate;
    private final LocalDateTime endDate;

    /**
     * @param id The autogenerated id for this record. null before saved into database.
     * @param employeeId The employee id this is for. Must be > 0.
     * @param responsibilityHeadCode The responsibility center head code. Cannot be null or empty string.
     * @param startDate The start date for this temp responsibility center assignment, inclusive. Cannot be null.
     * @param endDate The end date for this temp responsibility center assignment, inclusive. Cannot be null.
     */
    public TempResponsibilityHead(Integer id, int employeeId, String responsibilityHeadCode,
                                  LocalDateTime startDate, LocalDateTime endDate) {
        Preconditions.checkArgument(employeeId > 0);
        Preconditions.checkArgument(!responsibilityHeadCode.isEmpty());
        this.id = id;
        this.employeeId = employeeId;
        this.responsibilityHeadCode = Preconditions.checkNotNull(responsibilityHeadCode);
        this.startDate = Preconditions.checkNotNull(startDate);
        this.endDate = Preconditions.checkNotNull(endDate);
    }

    void setId(int id) {
        this.id = id;
    }

    Integer getId() {
        return id;
    }

    int getEmployeeId() {
        return employeeId;
    }

    String getResponsibilityHeadCode() {
        return responsibilityHeadCode;
    }

    LocalDateTime getStartDate() {
        return startDate;
    }

    LocalDateTime getEndDate() {
        return endDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TempResponsibilityHead that = (TempResponsibilityHead) o;
        return employeeId == that.employeeId &&
                Objects.equals(responsibilityHeadCode, that.responsibilityHeadCode) &&
                Objects.equals(startDate, that.startDate) &&
                Objects.equals(endDate, that.endDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(employeeId, responsibilityHeadCode, startDate, endDate);
    }
}
