
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = supply, pg_catalog;

Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BADGES', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BATTERIES', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BINDERS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/PUNCH', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BULLETIN/BOARDS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CALCULATOR/ACC', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BOOKS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CALENDARS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('DIARIES', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CARDBOARD', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CLIPS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('COMP/ACCESS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/COPIER', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/LOOSELEAF', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/STATIONER', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('KORECTYPE', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CUPS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BLOTTERS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BOOKENDS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('COMP/MOUSE', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('COPYHOLDERS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('DESK/ORGANIZER', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/ENVELOPES', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('FILES', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('GLUE', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('CARDS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('FAX/SUPPLIES', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('LABELS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BULBS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('COVERS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('DOOR/ACCESS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('LETTER/OPENER', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('RUBBERBAND', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('RULERS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('SCISSORS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('WASTE/REC', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('POST-IT', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PADS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/PADS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PAPER/GOODS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('MOISTENERS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('POSTAL/ACCESS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('ROLODEX', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('SEAL', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('INK/PAD', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('STAPLERS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('TAPES', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('BAGS', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('MARKERS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PENCILS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('PENS', 1);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('COMP/PR/RIBBON', 2);
Insert into supply.reconciliation_category_groups(item_category, page) VALUES ('TYPEWR/ACCESS', 2);