// services/attendanceService.js

export const fetchAttendanceRecords = async (year) => {
    // Simulate an API delay
    await new Promise((resolve) => setTimeout(resolve, 500));
  
    // Hardcoded data for testing
    const data = {
      active: [
        {
          dateRange: '5/23/2024 - 6/5/2024',
          payPeriod: '05',
          status: 'Not Submitted',
          work: 19,
          holiday: 7,
          vacation: 2,
          personal: 1.5,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 29.5,
        },
      ],
      submitted: [
        {
          dateRange: '5/9/2024 - 5/22/2024',
          payPeriod: '04',
          status: 'Personnel Approved',
          work: 70,
          holiday: 0,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '4/25/2024 - 5/8/2024',
          payPeriod: '03',
          status: 'Personnel Approved',
          work: 63.5,
          holiday: 0,
          vacation: 0,
          personal: 7,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70.5,
        },
        {
          dateRange: '4/11/2024 - 4/24/2024',
          payPeriod: '02',
          status: 'Personnel Approved',
          work: 68,
          holiday: 0,
          vacation: 0,
          personal: 2,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '3/28/2024 - 4/10/2024',
          payPeriod: '01',
          status: 'Personnel Approved',
          work: 49,
          holiday: 14,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '3/14/2024 - 3/27/2024',
          payPeriod: '26',
          status: 'Personnel Approved',
          work: 69,
          holiday: 0,
          vacation: 0,
          personal: 1.5,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70.5,
        },
        {
          dateRange: '2/29/2024 - 3/13/2024',
          payPeriod: '25',
          status: 'Personnel Approved',
          work: 66.5,
          holiday: 0,
          vacation: 0,
          personal: 1.5,
          sickEmp: 2,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '2/15/2024 - 2/28/2024',
          payPeriod: '24',
          status: 'Personnel Approved',
          work: 40.5,
          holiday: 7,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70.5,
        },
        {
          dateRange: '2/1/2024 - 2/14/2024',
          payPeriod: '23',
          status: 'Personnel Approved',
          work: 63,
          holiday: 7,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '1/18/2024 - 1/31/2024',
          payPeriod: '22',
          status: 'Personnel Approved',
          work: 62,
          holiday: 0,
          vacation: 0,
          personal: 3,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '1/4/2024 - 1/17/2024',
          payPeriod: '21',
          status: 'Personnel Approved',
          work: 61.5,
          holiday: 7,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 70,
        },
        {
          dateRange: '1/1/2024 - 1/3/2024',
          payPeriod: '20B',
          status: 'Personnel Approved',
          work: 14,
          holiday: 7,
          vacation: 0,
          personal: 0,
          sickEmp: 0,
          sickFam: 0,
          misc: 0,
          total: 21,
        },
      ],
    };
  
    return data;
  };
  