<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        New pending travel application for ${view.travelerFullName} on
        ${view.datesOfTravel}
    </title>
</head>
<body>
<p>
    <i>
        *** This is an automated message. Please do not reply to this email. ***
    </i>
</p>

<br/>
<p>
    Hi ${recipient.firstName},
</p>
<p>
    A Travel Application for ${view.travelerFullName} on ${view.datesOfTravel} is awaiting your review.
</p>
<p>
    <a href="${domainUrl}/travel/manage/review">Click here to review.</a>
</p>
<br/>
<p>
    Thank you.
</p>
</body>
</html>
